In [1]:
pip install pandas openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import os
from glob import glob

In [3]:
os.listdir(r"C:\Users\HP\Documents\celebal\celebal week 1 data")

['backpacks.csv',
 'bath-robe.csv',
 'bath-towels.csv',
 'bathroom-accessories.csv',
 'bedsheets.csv',
 'belts.csv',
 'bodysuit.csv',
 'boots.csv',
 'boxers.csv',
 'bra.csv',
 'bracelet.csv',
 'briefs.csv',
 'camisoles.csv',
 'candle-holders.csv',
 'caps.csv',
 'casual-shoes.csv',
 'chair-cover.csv',
 'clothing-set.csv',
 'clutches.csv',
 'co-ords.csv',
 'Combined_dataset.csv',
 'curtains-and-sheers.csv',
 'cutlery.csv',
 'dinnerware.csv',
 'dresses.csv',
 'duffel-bag.csv',
 'dungarees.csv',
 'dupatta.csv',
 'earrings.csv',
 'ethnic-dresses.csv',
 'face-moisturisers.csv',
 'face-wash-and-cleanser.csv',
 'flats.csv',
 'flip-flops.csv',
 'floor-mats--dhurries.csv',
 'formal-shoes.csv',
 'foundation.csv',
 'gloves.csv',
 'hair-accessory.csv',
 'hair-brush-and-comb.csv',
 'hair-cream-and-mask.csv',
 'hair-masks.csv',
 'handbags.csv',
 'headphones.csv',
 'heels.csv',
 'home-fragrance-set.csv',
 'innerwear-vests.csv',
 'jackets.csv',
 'jeans.csv',
 'jumpsuit.csv',
 'kurta-sets.csv',
 'kurtas.csv',
 'kurtis.csv',
 'lipstick.csv',
 'lounge-pants.csv',
 'lounge-shorts.csv',
 'lounge-tshirts.csv',
 'mangalsutra.csv',
 'mobile-accessories.csv',
 'night-suits.csv',
 'nightdress.csv',
 'outdoor-masks.csv',
 'palazzos.csv',
 'perfume-and-body-mist.csv',
 'pillow-covers.csv',
 'README.md',
 'ring.csv',
 'runners.csv',
 'sandals.csv',
 'saree-blouse.csv',
 'sarees.csv',
 'scarves.csv',
 'shampoo-and-conditioner.csv',
 'shaving-essentials.csv',
 'sherwani.csv',
 'shirts.csv',
 'shorts.csv',
 'showpieces.csv',
 'skirts.csv',
 'sports-shoes.csv',
 'sunglasses.csv',
 'sweaters.csv',
 'sweatshirts.csv',
 'swim-tops.csv',
 'table-covers.csv',
 'thermal-bottoms.csv',
 'tights.csv',
 'tops.csv',
 'towel-set.csv',
 'track-pants.csv',
 'trolley-bag.csv',
 'trousers.csv',
 'trunk.csv',
 'tshirts.csv',
 'tunics.csv',
 'wall-art.csv',
 'wallets.csv',
 'watches.csv',
 'yoga-mats.csv']

In [4]:
import pandas as pd
import os
from glob import glob

folder_path = r"C:\Users\HP\Documents\celebal\celebal week 1 data"

csv_files = glob(os.path.join(folder_path, "*.csv"))

print("CSV files found:", len(csv_files))

df_list = []

for file in csv_files:
    print("Loading:", os.path.basename(file))
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

print("\nCombined Shape:", df.shape)

df.head()

CSV files found: 98
Loading: backpacks.csv
Loading: bath-robe.csv
Loading: bath-towels.csv
Loading: bathroom-accessories.csv
Loading: bedsheets.csv
Loading: belts.csv
Loading: bodysuit.csv
Loading: boots.csv
Loading: boxers.csv
Loading: bra.csv
Loading: bracelet.csv
Loading: briefs.csv
Loading: camisoles.csv
Loading: candle-holders.csv
Loading: caps.csv
Loading: casual-shoes.csv
Loading: chair-cover.csv
Loading: clothing-set.csv
Loading: clutches.csv
Loading: co-ords.csv
Loading: Combined_dataset.csv
Loading: curtains-and-sheers.csv
Loading: cutlery.csv
Loading: dinnerware.csv
Loading: dresses.csv
Loading: duffel-bag.csv
Loading: dungarees.csv
Loading: dupatta.csv
Loading: earrings.csv
Loading: ethnic-dresses.csv
Loading: face-moisturisers.csv
Loading: face-wash-and-cleanser.csv
Loading: flats.csv
Loading: flip-flops.csv
Loading: floor-mats--dhurries.csv
Loading: formal-shoes.csv
Loading: foundation.csv
Loading: gloves.csv
Loading: hair-accessory.csv
Loading: hair-brush-and-comb.csv
Loading: hair-cream-and-mask.csv
Loading: hair-masks.csv
Loading: handbags.csv
Loading: headphones.csv
Loading: heels.csv
Loading: home-fragrance-set.csv
Loading: innerwear-vests.csv
Loading: jackets.csv
Loading: jeans.csv
Loading: jumpsuit.csv
Loading: kurta-sets.csv
Loading: kurtas.csv
Loading: kurtis.csv
Loading: lipstick.csv
Loading: lounge-pants.csv
Loading: lounge-shorts.csv
Loading: lounge-tshirts.csv
Loading: mangalsutra.csv
Loading: mobile-accessories.csv
Loading: night-suits.csv
Loading: nightdress.csv
Loading: outdoor-masks.csv
Loading: palazzos.csv
Loading: perfume-and-body-mist.csv
Loading: pillow-covers.csv
Loading: ring.csv
Loading: runners.csv
Loading: sandals.csv
Loading: saree-blouse.csv
Loading: sarees.csv
Loading: scarves.csv
Loading: shampoo-and-conditioner.csv
Loading: shaving-essentials.csv
Loading: sherwani.csv
Loading: shirts.csv
Loading: shorts.csv
Loading: showpieces.csv
Loading: skirts.csv
Loading: sports-shoes.csv
Loading: sunglasses.csv
Loading: sweaters.csv
Loading: sweatshirts.csv
Loading: swim-tops.csv
Loading: table-covers.csv
Loading: thermal-bottoms.csv
Loading: tights.csv
Loading: tops.csv
Loading: towel-set.csv
Loading: track-pants.csv
Loading: trolley-bag.csv
Loading: trousers.csv
Loading: trunk.csv
Loading: tshirts.csv
Loading: tunics.csv
Loading: wall-art.csv
Loading: wallets.csv
Loading: watches.csv
Loading: yoga-mats.csv

Combined Shape: (2000, 24)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [5]:
# exploring the data - first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
# exploring the data - ladt 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
1999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [7]:
#shape of the dataset 
print("shape : ",df.shape)

shape :  (2000, 24)

In [8]:
#column names
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [9]:
# data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2000 non-null   int64
 1   title                   2000 non-null   object
 2   product_description     2000 non-null   object
 3   rating                  2000 non-null   float64
 4   ratings_count           2000 non-null   int64
 5   initial_price           2000 non-null   float64
 6   discount                1758 non-null   float64
 7   final_price             2000 non-null   object
 8   currency                2000 non-null   object
 9   images                  2000 non-null   object
 10  delivery_options        2000 non-null   object
 11  product_details         2000 non-null   object
 12  breadcrumbs             2000 non-null   object
 13  product_specifications  2000 non-null   object
 14  amount_of_stars         2000 non-null   object
 15  what_customers_said     854 non-null    object
 16  seller_name             1398 non-null   object
 17  sizes                   2000 non-null   object
 18  videos                  438 non-null    object
 19  seller_information      1398 non-null   object
 20  variations              876 non-null    object
 21  best_offer              2000 non-null   object
 22  more_offers             2000 non-null   object
 23  category                2000 non-null   object
dtypes: float64(3), int64(2), object(19)
memory usage: 375.1+ KB

In [10]:
df.describe(include = 'all')

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,2.000000e+03,2000,2000,2000.000000,2000.000000,2000.000000,1758.000000,2000,2000,2000,...,2000,854,1398,2000,438,1398,876,2000,2000,2000
unique,NaN,454,989,NaN,NaN,NaN,NaN,466,1,1000,...,808,302,301,672,219,298,22,468,159,97
top,NaN,Roadster,Women Pink Solid Top,NaN,NaN,NaN,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,NaN,60,6,NaN,NaN,NaN,NaN,50,2000,2,...,228,54,80,270,2,80,252,612,530,244
mean,1.713437e+07,NaN,NaN,3.621500,76.691000,2723.241000,53.503982,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.812812e+06,NaN,NaN,1.374057,241.053946,2408.094809,18.024070,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,5.868460e+05,NaN,NaN,0.000000,0.000000,249.000000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.511501e+07,NaN,NaN,3.700000,7.000000,1399.000000,44.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.820890e+07,NaN,NaN,4.100000,17.000000,1999.000000,56.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.902737e+07,NaN,NaN,4.300000,58.000000,3299.000000,66.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.274707e+07,NaN,NaN,5.000000,4441.000000,22199.000000,88.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#handling missing values
missing_values= df.isnull().sum()
print(missing_values)

product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                   242
final_price                  0
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said       1146
seller_name                602
sizes                        0
videos                    1562
seller_information         602
variations                1124
best_offer                   0
more_offers                  0
category                     0
dtype: int64

In [12]:
#totaling all missing values
print("total missing values : ",df.isnull().sum().sum())

total missing values :  5278

In [13]:
#filling numeric missing values
numeric_cols= df.select_dtypes(include = ['number']).columns
for col in numeric_cols:
    df[col] =df[col].fillna(df[col].mean())

In [16]:
#filling text missing values
text_cols=df.select_dtypes(include=['object']).columns
for col in text_cols:
    df[col]=df[col].fillna('unknown')
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [18]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [21]:
#basic operations
#select columns
selected_columns =df[['title','rating','final_price']]
selected_columns.head()

            title  rating  final_price
0     Lino Perros     3.8  "₹3,995.00"
1  Tommy Hilfiger     4.5  "₹2,899.00"
2           Lavie     4.4  "₹2,999.00"
3          F Gear     4.4  "₹1,675.00"
4       MYTRIDENT     4.7  "₹2,899.00"

In [23]:
#products with rating greater than 4
high_rated_products=df[df['rating']>4]
high_rated_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",unknown,unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",unknown,unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.000000,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",unknown,unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",unknown,unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",unknown,unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",unknown,unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
6,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399.0,53.503982,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",unknown,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",unknown,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [24]:
#products with discount greater than 50%
high_discount_products=df[df['discount']>50]
high_discount_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.000000,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",unknown,unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",unknown,unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.000000,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",unknown,unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",unknown,unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
5,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399.0,65.000000,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",unknown,unknown,"[{""size"":""Onesize""}]",unknown,unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
6,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399.0,53.503982,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",unknown,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",unknown,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [30]:
df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [31]:
print(df['final_price'].dtype)

float64

In [33]:
#products worth more than 1000
expensive_products=df[df['final_price']>1000]
expensive_products.head()

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]

In [35]:
print("duplicates befpre cleaning : ",df.duplicated().sum())

duplicates befpre cleaning :  1000

In [36]:
df=df.drop_duplicates()
print("duplicates after cleaning : ",df.duplicated().sum())

duplicates after cleaning :  0

In [38]:
df = df.copy()
df['quantity']=1
df['total_amount']=df['final_price']*df['quantity']

In [41]:
df[['title','final_price','quantity','total_amount']].head()

            title  final_price  quantity  total_amount
0     Lino Perros          NaN         1           NaN
1  Tommy Hilfiger          NaN         1           NaN
2           Lavie          NaN         1           NaN
3          F Gear          NaN         1           NaN
4       MYTRIDENT          NaN         1           NaN

In [42]:
print(df[['final_price','quantity','total_amount']].dtypes)

final_price     float64
quantity          int64
total_amount    float64
dtype: object

In [44]:
df.to_csv('cleaned_dataset.csv',index=False)
print("cleaned dataset saved")

cleaned dataset saved

In [45]:
import os
print(os.path.exists('cleaned_dataset.csv'))

True

In [47]:
#verification
print("final shape : ",df.shape)

final shape :  (1000, 26)

In [48]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,NaN,INR,http://assets.myntassets.com/assets/images/837...,...,unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,NaN,INR,http://assets.myntassets.com/assets/images/913...,...,unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,NaN,INR,http://assets.myntassets.com/assets/images/176...,...,unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,NaN,INR,http://assets.myntassets.com/assets/images/137...,...,unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",unknown,unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,NaN,INR,http://assets.myntassets.com/assets/images/pro...,...,unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",unknown,unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,NaN

In [49]:
print(df.isnull().sum())

product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                     0
final_price               1000
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said          0
seller_name                  0
sizes                        0
videos                       0
seller_information           0
variations                   0
best_offer                   0
more_offers                  0
category                     0
quantity                     0
total_amount              1000
dtype: int64

In [52]:
print("remaining duplicates : ",df.duplicated().sum())

remaining duplicates :  0

In [ ]:
brief summary:

In this task, multiple product-related CSV files were imported and merged into a single Pandas DataFrame for analysis. After loading the data, an initial exploration was carried out using functions such as `head()`, `tail()`, `shape()`, `columns`, and `info()` to understand the structure and contents of the dataset.
The dataset was then examined for missing values and data quality issues. Missing entries were identified and handled appropriately to improve consistency. Duplicate records were detected and removed to avoid redundancy and ensure accurate analysis.
Basic data manipulation techniques were applied, including selecting specific columns and filtering records based on conditions such as product ratings, discounts, and prices. Since the dataset did not contain a quantity column, a default quantity value was introduced to demonstrate feature engineering. Using this value and the product's final price, a new column named `total_amount` was created.
Finally, the cleaned and transformed dataset was exported as a new CSV file. Through this exercise, key Pandas operations for data loading, exploration, cleaning, filtering, transformation, and exporting were successfully performed, resulting in a dataset that is better prepared for further analysis and reporting.